services:
  # main 서비스 (Nginx)
  service-docker-main:
    image: dkxm0908/nginx:1.29.7-docker-main
    container_name: docker-main-nginx-container
    restart: always
    ports:
      - "8080:80"
    networks:
      - board-network

  service-docker-install:
    image: dkxm0908/nginx:1.29.7-docker-install2
    container_name: docker-install-nginx-container
    restart: always
    ports:
      - "8081:80"
    networks:
      - board-network

  service-docker-fastapi:
    image: dkxm0908/fastapi:1.29.7-docker
    container_name: docker-fastapi-container
    restart: always
    ports:
      - "8000:80"
    networks:
      - board-network
      
      


networks:
  board-network:
    driver: bridge

